TaskManagement/Models/Task.cs
using System.ComponentModel.DataAnnotations;
using TaskManagement.Data.Enums;
using TaskManagement.Data.Interfaces;
using TaskManagement.ViewModels;

namespace TaskManagement.Models
{
  /// <summary>
  /// Модель задачи в БД
  /// </summary>
  public class Task : IEntity
  {
    /// <summary>
    /// Id задачи
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Наименование задачи
    /// </summary>
    [Required]
    [Display(Name = "Наименование")]
    public string Name { get; set; }

    /// <summary>
    /// Описание задачи
    /// </summary>
    [Required]
    [Display(Name = "Описание")]
    public string Description { get; set; }

    /// <summary>
    /// Приоритет задачи
    /// </summary>
    [Required]
    [Display(Name = "Приоритет")]
    public Priority Priority { get; set; }

    /// <summary>
    /// Статус задачи
    /// </summary>
    [Required]
    [Display(Name = "Статус")]
    public Status Status { get; set; }

    /// <summary>
    /// Дата завершения задачи
    /// </summary>
    [Required]
    [Display(Name = "Дата завершения")]
    [DataType(DataType.Date)]
    public DateTime DeadLine { get; set; }

    /// <summary>
    /// Наблюдатели задачи
    /// </summary>
    [Required]
    [Display(Name = "Наблюдатели")]
    public List<User?> Reviewers { get; set; } = new();

    /// <summary>
    /// Исполнители задачи
    /// </summary>
    [Required]
    [Display(Name = "Исполнители")]
    public List<User?> Executors { get; set; } = new();

    /// <summary>
    /// Комментарии задачи
    /// </summary>
    [Display(Name = "Комментарии")]
    public List<Comment?> Comments { get; set; } = new();

    public Task()
    {

    }

    public Task(TaskEditViewModel taskVM)
    {
      this.Name = taskVM.Name;
      this.Description = taskVM.Description;
      this.Status = taskVM.Status;
      this.Priority = taskVM.Priority;
      this.DeadLine = taskVM.DeadLine;
      this.Executors = taskVM.Executors;
      this.Comments = taskVM.Comments;
    }
  }
}

TaskManagement/Controllers/TasksController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TaskManagement.Data.Comparers;
using TaskManagement.Data.Interfaces;
using TaskManagement.Models;
using TaskManagement.Services;
using TaskManagement.Structs;
using TaskManagement.ViewModels;

namespace TaskManagement.Controllers
{
	/// <summary>
	/// Контроллер Задач
	/// </summary>
	public class TasksController : Controller
	{
		private readonly IUsersRepository _usersRepos;
		private readonly ITasksRepository _tasksRepos;
		private readonly ICommentRepository _commentsRepos;

		public TasksController(IUsersRepository users, ITasksRepository tasks,
			ICommentRepository comments)
		{
			_usersRepos = users;
			_tasksRepos = tasks;
			_commentsRepos = comments;
		}

		/// <summary>
		/// Метод для получения всех задач
		/// </summary>
		/// <returns></returns>
		[HttpGet]
		public async Task<IActionResult> Index()
		{
			if (User.Identity.IsAuthenticated)
			{
				var tasks = await _tasksRepos.GetAllAsync();
				var taskFilterVM = new TaskFilterViewModel(tasks);
				return View(taskFilterVM);
			}
			else
			{
				return RedirectToAction("Index", "Home");
			}
		}

		/// <summary>
		/// Фильтрация коллекции задач
		/// </summary>
		/// <param name="FilterText">Фильтрация по названию</param>
		/// <param name="highPriority">Включение задач с высоким приоритетом</param>
		/// <param name="mediumPriority">Включение задач с средним приоритетом</param>
		/// <param name="LowPriority">Включение задач с низким приоритетом</param>
		/// <param name="isReview">Включение задач со статусом "Review"</param>
		/// <param name="isInProgress">Включение задач со статусом "InProgress"</param>
		/// <param name="isExecRequired">Включение задач со статусом "isExecRequired"</param>
		/// <param name="isFinished">Включение задач со статусом "isFinished"</param>
		/// <param name="isUserLinked">Включение только тех задач, которые связаны с пользователем</param>
		/// <returns>Отфильтрованная коллекция задач</returns>
		[HttpPost]
		public async Task<IActionResult> Index(string FilterText, bool highPriority,
			bool mediumPriority, bool LowPriority, bool isReview, bool isInProgress,
			bool isExecRequired, bool isFinished, bool isUserLinked /*[FromBody] TaskFilterStruct jsonStructure*/)
		{
			var filters = new TaskFilterStruct(FilterText, highPriority,
			 mediumPriority, LowPriority, isReview, isInProgress,
			 isExecRequired, isFinished, isUserLinked);
			//TaskFilterStruct Filters = Newtonsoft.Json.JsonConvert.DeserializeObject<TaskFilterStruct>(jsonStructure);
			var tasks = await GetTasksWithFilter(filters);

			var taskFilterVM = new TaskFilterViewModel
				(tasks, filters);
			return View(taskFilterVM);
		}

		/// <summary>
		/// Отображение справочной информации задачи
		/// </summary>
		/// <param name="id">Id задачи</param>
		/// <returns>Модель, представляющая справочную информацию</returns>
		[HttpGet]
		public async Task<IActionResult> Details(Guid? id)
		{
			if (id == null)
				throw new NullReferenceException("Передан null параметр");

			var currentTask = await _tasksRepos.GetByIdAsync(id.Value);

			if (currentTask == null)
        throw new NullReferenceException("Задача не найдена");

			var TaskView = new TaskDetailsViewModel(currentTask);

			var CommentsView = new List<CommentDetailsViewModel>();

			var comments = await _commentsRepos.GetAllByTaskID(id.Value);
			foreach (var comm in comments)
			{
				var author = await _usersRepos.GetByIdAsync(comm.UserId.Value);
				var newCommentVM = new CommentDetailsViewModel(comm);
				newCommentVM.Author = author;
				CommentsView.Add(newCommentVM);
			}
			TaskView.CommentDetails = CommentsView;

			var currentExecs = await _tasksRepos.GetAllExeByIdAsync(id.Value);
			TaskView.Executors = currentExecs.ToList();

			var currentRevs = await _tasksRepos.GetAllRevByIdAsync(id.Value);
			TaskView.Reviewers = currentRevs.ToList();

			return View(TaskView);
		}

		/// <summary>
		/// Отображение окна для создания задачи
		/// </summary>
		/// <returns>Модель для создания</returns>
		public async Task<IActionResult> Create()
		{
			var vm = new TaskEditViewModel();

			var execs = await _usersRepos.GetAllAsync();
			vm.possibleExecutors = from item in execs
														 select new SelectListItem { Text = item.Username, Value = item.Id.ToString() };

			var reviews = await _usersRepos.GetAllAsync();
			vm.possibleReviewers = from item in reviews
														 select new SelectListItem { Text = item.Username, Value = item.Id.ToString() };
			return View(vm);
		}

		/// <summary>
		/// Post - создание задачи по входной модели
		/// </summary>
		/// <param name="model">Входная модель</param>
		/// <returns>Возврат к списку задач</returns>
		/// <exception cref="NullReferenceException"></exception>
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(TaskEditViewModel model)
		{
			var toAdd = new Models.Task(model);
			//toAdd = model.currentTask;
			if (toAdd == null)
				throw new NullReferenceException();

			foreach (var item in model.currentExecutors)
			{
				var tempUser = await _usersRepos.GetByIdAsync(Guid.Parse(item));
				if (tempUser == null)
					throw new NullReferenceException("Пользователь не определен");
				tempUser.Executors.Add(toAdd);
				_usersRepos.Update(tempUser);
				toAdd.Executors.Add(tempUser);
			}
			foreach (var item in model.currentReviewers)
			{
				var tempUser = await _usersRepos.GetByIdAsync(Guid.Parse(item));
				if (tempUser == null)
          throw new NullReferenceException("Пользователь не определен");
        tempUser.Reviewers.Add(toAdd);
				_usersRepos.Update(tempUser);
				toAdd.Reviewers.Add(tempUser);
			}
			var add = _tasksRepos.Update(toAdd);

			if (!add) throw new Exception("Не удалось создать задачу");

			return RedirectToAction("Index", "Home");
		}

		/// <summary>
		/// Отображение окна изменения задачи
		/// </summary>
		/// <param name="id">Id задачи</param>
		/// <returns></returns>
		[HttpGet]
		public async Task<IActionResult> Edit(Guid? id)
		{
			if (User.Identity?.IsAuthenticated != true)
				return RedirectToAction("Index", "Home");

			if (id == null)
				throw new NullReferenceException("Передан null параметр");

			var currentTask = await _tasksRepos.GetByIdAsync(id.Value);
			if (currentTask is null)
				return NotFound();

			var allUsers = await _usersRepos.GetAllAsync();

			var oldExecs = await _tasksRepos.GetAllExeByIdAsync(id.Value);
			var oldRevs = await _tasksRepos.GetAllRevByIdAsync(id.Value);

			var taskView = new TaskEditViewModel
				(
					currentTask,
					allUsers == null ? new List<User?>() : allUsers,
					oldExecs == null ? new List<User?>() : oldExecs,
					oldRevs == null ? new List<User?>() : oldRevs
				);

			return View(taskView);
		}

		/// <summary>
		/// Post - изменение задачи по входной модели
		/// </summary>
		/// <param name="model">Входная модель</param>
		/// <returns></returns>
		[HttpPost]
		public async Task<IActionResult> Edit(TaskEditViewModel model)
		{
			var toUpdate = await _tasksRepos.GetByIdAsync(model.Id);

			if (toUpdate == null)
        throw new NullReferenceException("Передан null параметр");

      //весь код ниже определяет выбранных пользователей в наблюдатели и исполнители
      var newRevList = new List<User?>();
			if (model.currentReviewers == null)
				newRevList = new List<User?>();
			else
				foreach (var item in model.currentReviewers)
				{
					var tempRev = await _usersRepos.GetByIdAsync(Guid.Parse(item));
					newRevList.Add(tempRev);
				}

			var newExecList = new List<User?>();
			if (model.currentExecutors == null)
				newExecList = new List<User?>();
			else
				foreach (var item in model.currentExecutors)
				{
					var tempExec = await _usersRepos.GetByIdAsync(Guid.Parse(item));
					newExecList.Add(tempExec);
				}

			//весь последующий код реализован для избежания ошибочных отправлений писем
			var oldLinkedUsers = await _tasksRepos.GetLinkedUsers(model.Id);
			var newLinkedUsers = new List<User?>(newRevList);
			newLinkedUsers.AddRange(newExecList);

			var fullUsers = oldLinkedUsers;
			fullUsers.AddRange(newLinkedUsers);
			var toEmail = fullUsers.Distinct(new UserEqualityComparer<User?>()).ToList();

			EmailService.sendEmailToUsers(toEmail, toUpdate, Data.Enums.Reason.Edit);

			//если закидывать в update model.currentTask - выкидывает ошибку, что таска с данным ID уже отслеживается
			//Если изменится ссылка, то выкидывает ошибку. не могу придумать как сделать
			toUpdate.Name = model.Name;
			toUpdate.Description = model.Description;
			toUpdate.Status = model.Status;
			toUpdate.Priority = model.Priority;
			toUpdate.DeadLine = model.DeadLine;
			toUpdate.Executors = newExecList == null ? new List<User?>() : newExecList;
			toUpdate.Reviewers = newRevList == null ? new List<User?>() : newRevList;

			var update = _tasksRepos.Update(toUpdate);

			if (!update) throw new Exception("Не удалось обновить задачу");

			return RedirectToAction("Index", "Home");
		}

		/// <summary>
		/// Отображение окна удаления задачи
		/// </summary>
		/// <param name="id"></param>
		/// <returns></returns>
		public async Task<IActionResult> Delete(Guid? id)
		{
			if (id == null)
        throw new NullReferenceException("Передан null параметр");

      var byIdAsync = await _tasksRepos.GetByIdAsync(id.Value);



			if (byIdAsync == null) return NotFound();

			return View(byIdAsync);
		}

		/// <summary>
		/// Подтверждение удаления задачи
		/// </summary>
		/// <param name="id"></param>
		/// <returns></returns>
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(Guid id)
		{
			if (User.Identity?.IsAuthenticated != true)
				return RedirectToAction("Index", "Home");

			var toDelete = await _tasksRepos.GetByIdAsync(id);
			if (toDelete == null)
        throw new NullReferenceException("Не удалось определить задачу");

TaskManagement/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Server.IISIntegration;
using TaskManagement.Data.Interfaces;
using TaskManagement.Models;
using TaskManagement.Structs;
using TaskManagement.ViewModels;

namespace TaskManagement.Controllers
{
  public class UsersController : Controller
  {
    private readonly IUsersRepository _usersRepos;

    public UsersController(IUsersRepository userRepos)
    {
      this._usersRepos = userRepos;
    }

    /// <summary>
    /// Отображение списка пользователей
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public async Task<IActionResult> Index()
    {
      var allUsers = await _usersRepos.GetAllAsync();
      var usersFilterVM = new UserFilterViewModel(allUsers);
      return View(usersFilterVM);
    }

    [HttpPost]
    public async Task<IActionResult> Index(string filterName, bool isAdmin,
      bool isModer, bool isDefault)
    {
      var userFilter = new UserFilterStruct(filterName, isAdmin, isModer, isDefault);
			
      var filteredUsers = await FilterUsers(userFilter);

      var usersFilterVM = new UserFilterViewModel(filteredUsers, userFilter);

			return View(usersFilterVM);
		}
    
    /// <summary>
    /// Фильтрация коллекции пользователей на основе фильтров
    /// </summary>
    /// <param name="Filters">Фильтры</param>
    /// <returns>Отфильтрованная коллекция</returns>
    private async Task<IEnumerable<User?>> FilterUsers(UserFilterStruct Filters)
    {
			var allUsers = await _usersRepos.GetAllAsync();

      allUsers = Filters.Filter(allUsers);

      return allUsers;
		}

		/// <summary>
		/// Получения окна информации о пользователе
		/// </summary>
		/// <param name="id"></param>
		/// <returns></returns>
		/// <exception cref="Exception"></exception>
		[HttpGet]
    public async Task<IActionResult> Details(Guid? id)
    {
      if (id == null)
        throw new Exception("Передан Null Параметр");

      var user = await _usersRepos.GetByIdAsync(id.Value);
      if (user == null)
        return NotFound();
      return View(user);
    }

    /// <summary>
    /// Получение окна изменения пользователя
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    /// <exception cref="NullReferenceException"></exception>
    [HttpGet]
    public async Task<IActionResult> Edit(Guid? id)
    {
      if (User.Identity?.IsAuthenticated != true)
        return RedirectToAction("Index", "Home");

      if (id == null)
        throw new NullReferenceException("Передан Null Параметр");

      var currentUser = await _usersRepos.GetByIdAsync(id.Value);
      if (currentUser is null)
        return NotFound();

      return View(currentUser);
    }

    /// <summary>
    /// Post - Изменение Пользователя
    /// </summary>
    /// <param name="id"></param>
    /// <param name="user"></param>
    /// <returns></returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(User user)
    {
      var updateResult = false;
      if (user != null)
        updateResult = _usersRepos.Update(user);

      if (!updateResult)
        throw new Exception("Не удалось обновить данные о пользователе");

      return RedirectToAction("Index");
    }

    /// <summary>
    /// Метод вызывающий удаление пользователя
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    /// <exception cref="NullReferenceException"></exception>
    [HttpGet]
    public async Task<IActionResult> Delete(Guid? id)
    {
      if (id == null)
        throw new NullReferenceException("Передан Null Параметр");

      var userToDelete = await _usersRepos.GetByIdAsync(id.Value);

      if (userToDelete == null)
        return NotFound();

      return View(userToDelete);
    }

    /// <summary>
    /// Окно подтверждения удаления пользователя
    /// </summary>
    /// <param name="id">Id пользователя</param>
    /// <returns></returns>
    /// <exception cref="Exception"></exception>
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(Guid id)
    {
      var userToDelete = await _usersRepos.GetByIdAsync(id);

      if (userToDelete == null)
        return NotFound();

      var res = _usersRepos.Delete(userToDelete);
      if (!res)
        throw new Exception("Произошла ошибка при удалении записи");

      var allUsers = await _usersRepos.GetAllAsync();
      var usersFilterVM = new UserFilterViewModel(allUsers);
      return View("Index", usersFilterVM);
    }
  }
}

TaskManagement/Views/Tasks/Create.cshtml
@using TaskManagement.Data.Enums
@model TaskManagement.ViewModels.TaskEditViewModel

@{
    ViewData["Title"] = "Create";
}
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Priority" class="control-label"></label>
                <select asp-for="Priority" class="form-control"
                        asp-items="@(Html.GetEnumSelectList<Priority>())"></select>
                <span asp-validation-for="Priority" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control"
                        asp-items="@(Html.GetEnumSelectList<Status>())"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="row mb-3">
                <label class="col-sm-3 col-form-label" asp-for="currentExecutors">Executors</label>
                <div class="col-sm-6">
                  <select multiple class="form-control text-center"
                          asp-for="currentExecutors"
                          asp-items="@(Model.possibleExecutors)"
                          required>
                  </select>
                </div>
            </div>
            <div class="row mb-3">
                <label class="col-sm-3 col-form-label" asp-for="currentReviewers">Reviewers</label>
                <div class="col-sm-6">
                  <select multiple class="form-control text-center"
                          asp-for="currentReviewers"
                          asp-items="@(Model.possibleReviewers)"
                          required>
                  </select>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="DeadLine" class="control-label"></label>
                <input asp-for="DeadLine" class="form-control" />
                <span asp-validation-for="DeadLine" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-primary mt-1" asp-action="Index">Вернуться к задачам</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TaskManagement/Views/Tasks/Delete.cshtml
@model TaskManagement.Models.Task

@{
    ViewData["Title"] = "Удаление задачи";
}

<h3>Подтвердите удаление.</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Priority)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Priority)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DeadLine)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DeadLine)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
    </form>
</div>

TaskManagement/Views/Tasks/Details.cshtml
@using TaskManagement.Data.Enums
@model TaskManagement.ViewModels.TaskDetailsViewModel

@{
    ViewData["Title"] = "Информация о задаче";
}

<div class="container card p-2" style="border-radius: 15px">
  <div class="row">
    @*Инфа о таске*@
    <div class="col-7">
      <div class="p-5 mb-4 bg-body-tertiary" style="border-radius: 15px">
        <div class="container-fluid py-5">
          <div class="text-center">
            <h1 class="display-5 fw-bold">@Model.Name</h1>
            <p class="m-5 fs-4">@Model.Description</p>
          </div>
          <div class="">
            <p class="display-6">@Html.DisplayNameFor(x => @Model.DeadLine)</p>
            <p>@Model.DeadLine</p>
          </div>
          <div class="">
            <p class="display-6">@Html.DisplayNameFor(x => @Model.Priority)</p>
            <div>
              @if (Model.Priority == Priority.Low)
              {
                <small class="text-body-secondary badge rounded-pill bg-secondary">@Model.Priority</small>
              }
              @if (Model.Priority == Priority.Medium)
              {
                <small class="text-body-secondary badge rounded-pill bg-warning">@Model.Priority</small>
              }
              @if (Model.Priority == Priority.High)
              {
                <small class="text-body-secondary badge rounded-pill bg-danger">@Model.Priority</small>
              }
            </div>
          </div>
          <div class="">
            <p class="display-6">@Html.DisplayNameFor(x => @Model.Status)</p>
            <div>
              @if (Model.Status == Status.Finished)
              {
                <small class="text-body-secondary badge rounded-pill bg-secondary">@Model.Status</small>
              }
              @if (Model.Status == Status.Review)
              {
                <small class="text-body-secondary badge rounded-pill bg-primary">@Model.Status</small>
              }
              @if (Model.Status == Status.ExecutorRequired)
              {
                <small class="text-body-secondary badge rounded-pill bg-warning">@Model.Status</small>
              }
              @if (Model.Status == Status.InProgress)
              {
                <small class="text-body-secondary badge rounded-pill bg-success">@Model.Status</small>
              }
            </div>
          </div>
        </div>
      </div>
      <a type="button" class="w-100 btn btn-lg btn-outline-primary" asp-controller="Tasks" asp-action="Edit" asp-route-id="@Model.Id">Изменить</a>
      <a type="button" class="w-100 btn btn-lg btn-outline-danger" asp-controller="Tasks" asp-action="Delete" asp-route-id="@Model.Id">Удалить</a>
      <div class="d-flex justify-content-sm-evenly align-items-sm-start" style="padding-top: 20px">
        <div class="">
          <h3 class="text-center">@Html.DisplayNameFor(x => @Model.Reviewers)</h3>
          <div class="container-fluid">
            @foreach (var item in Model.Reviewers)
            {
              <div class="list-group mb-3">
                <div class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
                  <div class="d-flex gap-2 w-100 justify-content-center">
                    <div>
                      <h6 class="mb-0">@item.Username</h6>
                      <p class="mb-0 opacity-75">@item.Email</p>
                      <a href="@Url.Action("Details","Users",new{ id = item.Id})" class="stretched-link"></a>
                    </div>
                  </div>
                </div>
              </div>
            }
          </div>
        </div>
        <div class="">
          <h3 class="text-center">@Html.DisplayNameFor(x => @Model.Executors)</h3>
          <div class="container-fluid">
            @foreach (var item in Model.Executors)
            {
              <div class="list-group mb-3">
                <div class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
                  <div class="d-flex gap-2 w-100 justify-content-center">
                    <div>
                      <h6 class="mb-0">@item.Username</h6>
                      <p class="mb-0 opacity-75">@item.Email</p>
                      <a href="@Url.Action("Details","Users",new{ id = item.Id})" class="stretched-link"></a>
                    </div>
                  </div>
                </div>
              </div>
            }
          </div>
        </div>
      </div>
    </div>
    @*Комменты*@
    <div class="col-sm">
      <div class="card p-2 mb-1 bg-body-teriary h-100" style="border-radius: 15px;">
        <div class="container" style="padding-left: 5px">
          @if ((Model.Comments == null) || (Model.Comments.Count() == 0))
          {
            <label style="padding-left: 5px">Комментариев пока нет...</label>
          }
          @foreach (var comment in Model.CommentDetails)
          {
            <div class="row pt-2">
              <label style="font-weight: lighter; padding-left: 7px">@comment.CreatedAt</label>
              <div class="container-fluid" style="">
                <label style="font-weight: bold">@comment.Author.Username :</label>
                <label style="padding-left: 5px">@comment.Message</label>
              </div>
            </div>
          }
        </div>
        <div class="row pt-4">
          <form asp-action="AddComment" asp-controller="Tasks" method="post" style="display: inline-flex;">
            <input type="hidden" name="taskId" class="form-control" value="@Model.Id" />
            <input type="text" placeholder="Написать комментарий..." class="form-control d-inline p-2 h-100" name="commentText" style="border-bottom-left-radius: 33px; border-top-left-radius: 33px" />
            <button type="submit" class="form-control-sm d-inline p-2 h-100 w-50" style="color:#fff;background-color: #0d6efd; border-color: #0d6efd; border-top-right-radius: 33px; border-bottom-right-radius: 33px">Отправить</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>